vim.cmd('source /home/maojingwei/project/common_tools_for_centos/init_nvim.vim')
--
--
--
--
--vim.api.nvim_set_keymap(
--  "n",
--  "<space>fb",
--  ":Telescope file_browser<CR>",
--  { noremap = true }
--)
--
--vim.api.nvim_set_keymap(
--  "n",
--  "<space>fb",
--  ":Telescope file_browser path=%:p:h select_buffer=true<CR>",
--  { noremap = true }
--)
