font_family      JetBrainsMono Nerd Font
font_size        20
macos_option_as_alt yes
background            #ffffff
foreground            #000000
cursor                #000000
cursor_text_color     #ffffff
cursor_shape          block
cursor_blink_interval 0
remember_window_position yes

map ctrl+j send_text all \x1b[25~
map ctrl+k send_text all \x1b[26~
